package com.example.kitchensink.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * MongoDB Document for storing Refresh Tokens
 */
@Document(collection = "refreshTokens")
@Data
public class RefreshToken {

    @Id
    private String id;

    @DBRef // Creates a database reference to the User document
    private User user;

    private String token; // The actual refresh token string

    private Instant expiryDate; // Expiration timestamp

    // Constructors, Getters, Setters will be generated by Lombok @Data
}